[area-1]
name = 'Area 1: Photonics & Semiconductor Physics'
courses = [
	'ECE318H1',
	'ECE330H1',
	'ECE335H1',
	'ECE427H1',
	'ECE437H1',
	'ECE469H1',
]

[area-2]
name = 'Area 2: Electromagnetics & Energy Systems'
courses = [
	'BME595H1',
	'ECE313H1',
	'ECE314H1',
	'ECE320H1',
	'ECE413H1',
	'ECE422H1',
	'ECE424H1',
	'ECE463H1',
	'ECE520H1',
	'ECE524H1',
	'ECE526H1',
]

[area-3]
name = 'Area 3: Analog & Digital Electronics'
courses = [
	'ECE331H1',
	'ECE334H1',
	'ECE412H1',
	'ECE424H1',
	'ECE430H1',
	'ECE437H1',
	'ECE446H1',
	'ECE512H1',
	'ECE524H1',
	'ECE530H1',
	'ECE532H1',
]

[area-4]
name = 'Area 4: Control, Communications & Signal Processing'
courses = [
	'BME331H1',
	'BME445H1',
	'BME595H1',
	'ECE302H1',
	'ECE311H1',
	'ECE316H1',
	'ECE368H1',
	'ECE410H1',
	'ECE411H1',
	'ECE417H1',
	'ECE421H1',
	'ECE422H1',
	'ECE431H1',
	'ECE441H1',
	'ECE445H1',
	'ECE446H1',
	'ECE462H1',
	'ECE464H1',
	'ECE469H1',
	'ECE470H1',
	'ECE516H1',
	'ECE537H1',
]

[area-5]
name = 'Area 5: Computer Hardware & Computer Networks'
courses = [
	'ECE302H1',
	'ECE342H1',
	'ECE361H1',
	'ECE461H1',
	'ECE462H1',
	'ECE464H1',
	'ECE466H1',
	'ECE469H1',
	'ECE532H1',
	'ECE537H1',
	'ECE552H1',
	'ECE568H1',
]

[area-6]
name = 'Area 6: Software'
courses = [
	'APS360H1',
	'CSC317H1',
	'CSC326H1',
	'CSC343H1',
	'CSC343H5',
	'CSC418H1',
	'CSC444H1',
	'CSC467H1',
	'ECE326H1',
	'ECE344H1',
	'ECE345H1',
	'ECE419H1',
	'ECE444H1',
	'ECE448H1',
	'ECE454H1',
	'ECE461H1',
	'ECE467H1',
	'ECE568H1',
]

[area-7]
name = 'Area 7: Science/Math Electives'
courses = [
	'BME331H1',
	'BME440H1',
	'BME455H1',
	'CHE353H1',
	'CHE354H1',
	'CIV220H1',
	'CIV300H1',
	'ECE302H1',
	'ECE330H1',
	'ECE367H1',
	'ECE368H1',
	'ECE448H1',
	'ECE537H1',
	'ESC384H1',
	'PHY365H1',
]
